# Generated by Django 5.2 on 2025-08-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifSn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
                ('formhub_uuid', models.TextField(blank=True, null=True)),
                ('grp4_departement', models.TextField(blank=True, null=True)),
                ('grp4_region', models.TextField(blank=True, null=True)),
                ('meta_instanceid', models.TextField(blank=True, null=True)),
                ('meta_rootuuid', models.TextField(blank=True, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('type_de_campagne', models.TextField(blank=True, null=True)),
                ('instance_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('xform_id_string', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_time', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'objectif_sn_objectifsn',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ObjectifSnChild0c8ff1d1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_index', models.IntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('commune', models.TextField(blank=True, null=True)),
                ('effectif_cible', models.IntegerField(blank=True, null=True)),
                ('effectif_elligible', models.IntegerField(blank=True, null=True)),
                ('maladie_masse', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grp5_items', to='objectif_sn.objectifsn')),
            ],
            options={
                'db_table': 'objectif_sn_objectifsnchild0c8ff1d1',
                'ordering': ('parent_id', 'item_index'),
                'unique_together': {('parent', 'item_index')},
            },
        ),
    ]
