# Generated by Django 5.0.3 on 2025-02-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Partenaire", "0001_initial"),
        ("Pays", "0002_alter_pays_nom"),
        ("Structure", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom_du_produit", models.CharField(max_length=255)),
                (
                    "classe_therapeutique",
                    models.CharField(
                        choices=[
                            ("ANTIMICROBIEN", "Antimicrobien"),
                            ("ANTI_INFLAMMATOIRE", "Anti-inflammatoire"),
                            ("VACCIN", "Vaccin"),
                            ("ANALGESIQUE", "Analgésique"),
                            ("HORMONE", "Hormone"),
                            ("SUPPLEMENT_NUTRITIONNEL", "Supplément nutritionnel"),
                            ("ANESTHESIQUE", "Anesthésique"),
                            ("SEDATIF", "Sédatif"),
                            ("DIURETIQUE", "Diurétique"),
                            ("CARDIOVASCULAIRE", "Cardiovasculaire"),
                            ("ANTIHISTAMINIQUE", "Antihistaminique"),
                            ("ANTIDIARRHEIQUE", "Antidiarrhéique"),
                            ("LAXATIF", "Laxatif"),
                            ("IMMUNOSUPPRESSEUR", "Immunosuppresseur"),
                            ("ANTINEOPLASIQUE", "Antinéoplasique"),
                            ("TOPIQUE", "Topique"),
                        ],
                        default="ANTIMICROBIEN",
                        max_length=50,
                    ),
                ),
                (
                    "familles_antibiotiques",
                    models.CharField(
                        choices=[
                            ("AMINOSIDE", "Aminoside"),
                            ("FLUOROQUINOLONE", "Fluoroquinolone"),
                            ("MACROLIDE", "Macrolide"),
                            ("QUINOLONE", "Quinolone (Autres)"),
                            ("PENICILLINE", "Pénicilline"),
                            ("POLYPEPTIDE", "Polypeptide"),
                            ("SULFONAMIDE", "Sulfonamide (Triméthoprime inclus)"),
                            ("TETRACYCLINE", "Tétracycline"),
                            (
                                "ASSO_AMINOSIDE_TETRACYCLINE",
                                "Association Aminoside + Tétracycline",
                            ),
                            (
                                "ASSO_AMINOSIDE_PENICILLINE",
                                "Association Aminoside + Pénicilline",
                            ),
                            (
                                "ASSO_AMINOSIDE_SULFONAMIDE",
                                "Association Aminoside + Sulfonamide",
                            ),
                            (
                                "ASSO_FLUOROQUINOLONE_POLYPEPTIDE",
                                "Association Fluoroquinolone + Polypeptide",
                            ),
                            (
                                "ASSO_MACROLIDE_NITROIMIDAZOLE",
                                "Association Macrolide + Nitroimidazole",
                            ),
                            (
                                "ASSO_POLYPEPTIDE_TETRACYCLINE",
                                "Association Polypeptide + Tétracycline",
                            ),
                            (
                                "ASSO_PENICILLINE_POLYPEPTIDE",
                                "Association Pénicilline + Polypeptide",
                            ),
                            (
                                "ASSO_SULFONAMIDE_POLYPEPTIDE",
                                "Association Sulfonamide + Polypeptide",
                            ),
                            (
                                "ASSO_SULFONAMIDE_NITROFURANE",
                                "Association Sulfonamide + Nitrofuranes",
                            ),
                            (
                                "ASSO_TETRACYCLINE_NITROFURANE",
                                "Association Tétracycline + Nitrofuranes",
                            ),
                            (
                                "ASSO_TETRACYCLINE_MACROLIDE_POLYPEPTIDE",
                                "Association Tétracycline + Macrolide + Polypeptide",
                            ),
                        ],
                        default="AMINOSIDE",
                        max_length=100,
                    ),
                ),
                ("forme_pharmaceutique", models.CharField(max_length=255)),
                ("substances_actives", models.CharField(max_length=255)),
                (
                    "numero_autorisation_AMM",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "numero_decision_AMM",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_delivrance_AMM", models.DateField(blank=True, null=True)),
                (
                    "status_AMM",
                    models.CharField(
                        choices=[("ACTIF", "Actif"), ("NON_ACTIF", "Non actif")],
                        default="ACTIF",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enregistrement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_enregistrement",
                    models.CharField(
                        choices=[
                            ("FABRICATION", "Fabrication"),
                            ("IMPORTATION", "Importation"),
                            ("DOTATION", "Dotation"),
                            ("EXPORTATION", "Exportation"),
                        ],
                        default="IMPORTATION",
                        max_length=50,
                    ),
                ),
                (
                    "quantité_de_la_dotation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date_dotation", models.DateField(blank=True, null=True)),
                (
                    "adresse_partenaire_dotation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantité_fabriquée",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date_de_fabrication", models.DateField(blank=True, null=True)),
                (
                    "quantité_importée",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "addresse_importateur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_importation", models.DateField(blank=True, null=True)),
                (
                    "quantité_exportée",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "addresse_exportateur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_exportation", models.DateField(blank=True, null=True)),
                (
                    "valeur_financiere",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "unité_de_la_quantité",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firme_de_fabrication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Structure.structure",
                    ),
                ),
                (
                    "partenaire_de_dotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Partenaire.partenaire",
                    ),
                ),
                (
                    "pays_exportation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pays_exportation",
                        to="Pays.pays",
                    ),
                ),
                (
                    "pays_importation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pays_importation",
                        to="Pays.pays",
                    ),
                ),
                (
                    "structure_exportatrice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exportateur",
                        to="Structure.structure",
                    ),
                ),
                (
                    "structure_importatrice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importateur",
                        to="Structure.structure",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produit.produit",
                    ),
                ),
            ],
        ),
    ]
