# Generated by Django 5.0.3 on 2025-02-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pays", "0002_alter_pays_nom"),
        ("Structure", "0001_initial"),
        ("produit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enregistrement",
            name="pays_de_fabrication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pays_de_fabrication",
                to="Pays.pays",
            ),
        ),
        migrations.AlterField(
            model_name="enregistrement",
            name="firme_de_fabrication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Fabricant",
                to="Structure.structure",
            ),
        ),
    ]
