# Generated by Django 5.2 on 2025-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_alter_enregistrement_user_alter_produit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(choices=[('MEDICAMENT', 'Médicament vétérinaire'), ('SEMENCE_ANIMALE', 'Semence animale'), ('MATERIEL_VETERINAIRE', 'Matériel à usage vétérinaire')], default='MEDICAMENT', max_length=50, verbose_name='Type de produit'),
        ),
    ]
