# Generated by Django 5.2 on 2025-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_produit_type_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='classe_therapeutique',
            field=models.CharField(choices=[('ANTIMICROBIEN', 'Antimicrobien'), ('ANTI_INFLAMMATOIRE', 'Anti-inflammatoire'), ('VACCIN', 'Vaccin'), ('ANALGESIQUE', 'Analgésique'), ('HORMONE', 'Hormone'), ('SUPPLEMENT_NUTRITIONNEL', 'Supplément nutritionnel'), ('ANESTHESIQUE', 'Anesthésique'), ('SEDATIF', 'Sédatif'), ('DIURETIQUE', 'Diurétique'), ('CARDIOVASCULAIRE', 'Cardiovasculaire'), ('ANTIHISTAMINIQUE', 'Antihistaminique'), ('ANTIDIARRHEIQUE', 'Antidiarrhéique'), ('LAXATIF', 'Laxatif'), ('IMMUNOSUPPRESSEUR', 'Immunosuppresseur'), ('ANTINEOPLASIQUE', 'Antinéoplasique'), ('TOPIQUE', 'Topique')], default='ANTIMICROBIEN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='familles_antibiotiques',
            field=models.CharField(choices=[('AMINOSIDE', 'Aminoside'), ('FLUOROQUINOLONE', 'Fluoroquinolone'), ('MACROLIDE', 'Macrolide'), ('QUINOLONE', 'Quinolone (Autres)'), ('PENICILLINE', 'Pénicilline'), ('POLYPEPTIDE', 'Polypeptide'), ('SULFONAMIDE', 'Sulfonamide (Triméthoprime inclus)'), ('TETRACYCLINE', 'Tétracycline'), ('ASSO_AMINOSIDE_TETRACYCLINE', 'Association Aminoside + Tétracycline'), ('ASSO_AMINOSIDE_PENICILLINE', 'Association Aminoside + Pénicilline'), ('ASSO_AMINOSIDE_SULFONAMIDE', 'Association Aminoside + Sulfonamide'), ('ASSO_FLUOROQUINOLONE_POLYPEPTIDE', 'Association Fluoroquinolone + Polypeptide'), ('ASSO_MACROLIDE_NITROIMIDAZOLE', 'Association Macrolide + Nitroimidazole'), ('ASSO_POLYPEPTIDE_TETRACYCLINE', 'Association Polypeptide + Tétracycline'), ('ASSO_PENICILLINE_POLYPEPTIDE', 'Association Pénicilline + Polypeptide'), ('ASSO_SULFONAMIDE_POLYPEPTIDE', 'Association Sulfonamide + Polypeptide'), ('ASSO_SULFONAMIDE_NITROFURANE', 'Association Sulfonamide + Nitrofuranes'), ('ASSO_TETRACYCLINE_NITROFURANE', 'Association Tétracycline + Nitrofuranes'), ('ASSO_TETRACYCLINE_MACROLIDE_POLYPEPTIDE', 'Association Tétracycline + Macrolide + Polypeptide')], default='AMINOSIDE', max_length=100, null=True),
        ),
    ]
