# Generated by Django 5.2 on 2025-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_alter_produit_classe_therapeutique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='forme_pharmaceutique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='status_AMM',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('NON_ACTIF', 'Non actif')], default='ACTIF', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='substances_actives',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
