# Generated by Django 5.2 on 2025-08-23 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commune', '0003_alter_commune_user'),
        ('Departement', '0003_alter_departement_user'),
        ('Espece', '0006_alter_espece_user'),
        ('Maladie', '0006_alter_maladie_user'),
        ('Region', '0002_region_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('prochaine_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotReactif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('lot', models.CharField(max_length=60)),
                ('perime_le', models.DateField()),
                ('quantite', models.FloatField(default=0.0)),
                ('unite', models.CharField(default='u', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_test', models.CharField(max_length=40, unique=True)),
                ('nom_test', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('PCR', 'PCR'), ('Serologie', 'Sérologie/ELISA'), ('Bacterio', 'Bactériologie'), ('Parasito', 'Parasitologie'), ('Histo', 'Histopathologie')], max_length=20)),
                ('cible', models.CharField(blank=True, max_length=120)),
                ('methode', models.CharField(choices=[('RT_qPCR', 'RT-qPCR'), ('PCR_classique', 'PCR classique'), ('ELISA_I', 'ELISA Indirecte'), ('ELISA_C', 'ELISA Compétitive'), ('IFAT', 'IFAT'), ('Culture', 'Culture'), ('Microscopie', 'Microscopie'), ('Test_rapide', 'Test rapide')], max_length=30)),
                ('unite', models.CharField(blank=True, max_length=40)),
                ('seuil_decision', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_demande', models.CharField(help_text='Identifiant de la demande', max_length=30, unique=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('recue', 'Reçue'), ('en_analyse', 'En analyse'), ('valide_tech', 'Validée technique'), ('valide_bio', 'Validée biologique'), ('rapportee', 'Rapportée'), ('annulee', 'Annulée')], db_index=True, default='soumise', max_length=20)),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recu_le', models.DateTimeField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region')),
                ('site_labo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.sitelabo')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_echantillon', models.CharField(max_length=40, unique=True)),
                ('matrice', models.CharField(blank=True, max_length=100)),
                ('id_animal', models.CharField(blank=True, max_length=60)),
                ('date_prelevement', models.DateField(blank=True, null=True)),
                ('non_conformite', models.CharField(blank=True, max_length=200)),
                ('commentaire', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echantillons', to='lims.demande')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espece.espece')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maladie.maladie')),
            ],
        ),
        migrations.CreateModel(
            name='Soumissionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=120)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='soumissionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.soumissionnaire'),
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('valide_tech', 'Validée technique'), ('valide_bio', 'Validée biologique')], db_index=True, default='nouvelle', max_length=20)),
                ('resultat_brut', models.JSONField(blank=True, default=dict)),
                ('interpretation', models.CharField(blank=True, max_length=40)),
                ('debute_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('analyste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('echantillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='lims.echantillon')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.testcatalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('fichier_pdf', models.FileField(blank=True, upload_to='lims/rapports/')),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='lims.demande')),
                ('signe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_signes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'unique_together': {('demande', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['etat', 'cree_le'], name='lims_demand_etat_985d99_idx'),
        ),
        migrations.AddIndex(
            model_name='analyse',
            index=models.Index(fields=['etat'], name='lims_analys_etat_64f5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyse',
            index=models.Index(fields=['termine_le'], name='lims_analys_termine_566333_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyse',
            unique_together={('echantillon', 'test')},
        ),
    ]
