# Generated by Django 5.2 on 2025-08-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maladie', '0006_alter_maladie_user'),
        ('lims', '0002_emplacement_gabaritrapport_maintenance_piecejointe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='maladie',
        ),
        migrations.AddField(
            model_name='testcatalogue',
            name='maladie',
            field=models.ForeignKey(blank=True, help_text='Maladie/agent ciblé par ce test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Maladie.maladie'),
        ),
    ]
