# Generated by Django 5.2 on 2025-08-26 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_remove_echantillon_maladie_testcatalogue_maladie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='suspicion_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='suspicion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='suspicion_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_conclues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='suspicion_statut',
            field=models.CharField(choices=[('non_evaluee', 'Non évaluée'), ('confirmee', 'Confirmée'), ('infirmee', 'Infirmée')], default='non_evaluee', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalyseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(blank=True, help_text='ex: assignation, demarrage, resultat, validation_tech, validation_bio', max_length=30)),
                ('texte', models.TextField()),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lims.analyse')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
