# Generated by Django 5.2 on 2025-08-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_remove_echantillon_code_barres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='matrice',
            field=models.CharField(choices=[('serum', 'Sérum'), ('plasma', 'Plasma'), ('sang_total', 'Sang total'), ('buffy_coat', 'Buffy coat'), ('dbs_fta', 'Sang séché (DBS/FTA)'), ('ecouv_oropharynge', 'Écouvillon oropharyngé'), ('ecouv_nasal', 'Écouvillon nasal'), ('ecouv_tracheal', 'Écouvillon trachéal'), ('ecouv_cloacal', 'Écouvillon cloacal'), ('ecouv_rectal', 'Écouvillon rectal'), ('ecouv_anal', 'Écouvillon anal'), ('ecouv_buccal', 'Écouvillon buccal/oral'), ('ecouv_conjonctival', 'Écouvillon conjonctival/oculaire'), ('ecouv_vaginal', 'Écouvillon vaginal'), ('ecouv_preputial', 'Écouvillon préputial'), ('ecouv_cutane', 'Écouvillon cutané/plaie'), ('ecouv_carcasse', 'Écouvillon de carcasse (surface)'), ('salive', 'Salive'), ('lait', 'Lait'), ('colostrum', 'Colostrum'), ('urine', 'Urine'), ('bile', 'Bile'), ('lcr', 'Liquide céphalo-rachidien'), ('liq_pleural', 'Liquide pleural'), ('liq_peritoneal', 'Ascite / Liquide péritonéal'), ('liq_synovial', 'Liquide synovial'), ('semen', 'Sperme'), ('sec_nasale', 'Sécrétion nasale'), ('sec_vaginale', 'Sécrétion vaginale'), ('sec_uterine', 'Sécrétion utérine'), ('fiente', 'Fiente / Fèces'), ('copro', 'Copro (flottation / sédimentation)'), ('t_poumon', 'Tissu – Poumon'), ('t_foie', 'Tissu – Foie'), ('t_rate', 'Tissu – Rate'), ('t_rein', 'Tissu – Rein'), ('t_coeur', 'Tissu – Cœur'), ('t_cerveau', 'Tissu – Cerveau'), ('t_amygdale', 'Tissu – Amygdales'), ('t_ganglion', 'Tissu – Ganglion'), ('t_intestin', 'Tissu – Intestin'), ('t_pancreas', 'Tissu – Pancréas'), ('t_rate_rein', 'Tissu – Rate/Rein (petits ruminants/peste)'), ('muscle', 'Muscle'), ('peau', 'Peau'), ('plumes', 'Plumes'), ('poils', 'Poils'), ('os', 'Os'), ('moelle', 'Moelle osseuse'), ('ffpe', 'Bloc/paraffine (FFPE)'), ('Tetes', 'Tete'), ('placenta', 'Placenta'), ('avorton', 'Fœtus/avorton (pool tissus)'), ('oeuf_contenu', 'Œuf – contenu'), ('oeuf_coquille', 'Œuf – coquille'), ('embryon', 'Embryon'), ('poisson_rein_ant', 'Poisson – Rein antérieur'), ('poisson_rate', 'Poisson – Rate'), ('poisson_foie', 'Poisson – Foie'), ('poisson_coeur', 'Poisson – Cœur'), ('poisson_intestin', 'Poisson – Intestin'), ('poisson_branchies', 'Poisson – Branchies'), ('poisson_mucus', 'Poisson – Mucus/Peau'), ('poisson_nageoire', 'Poisson – Nageoire'), ('oeufs_poisson', 'Œufs de poisson'), ('abeilles_adultes', 'Abeilles adultes'), ('larves_abeilles', 'Larves d’abeilles'), ('miel', 'Miel'), ('tiques', 'Tiques / Ectoparasites'), ('insectes', 'Insectes (pool/individus)'), ('larves', 'Larves'), ('fourrage', 'Fourrage / Aliments'), ('eau', 'Eau'), ('sol', 'Sol / Boue / Poussières'), ('air', 'Air (filtre/impacteur)'), ('culture_bouillon', 'Culture – Bouillon'), ('culture_gelose', 'Culture – Gélose'), ('isole', 'Isolat (culture pure)'), ('autre', 'Autre (préciser)')], db_index=True, max_length=40),
        ),
    ]
