# Generated by Django 5.2 on 2025-08-26 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_alter_echantillon_matrice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(blank=True, max_length=40)),
                ('texte', models.TextField()),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lims.demande')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('val_tech', 'Validation technique'), ('val_bio', 'Validation biologique'), ('saisie_resultats', 'Saisie des résultats'), ('analyse_exec', 'Exécution d’analyses')], max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='lims.demande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['demande', 'role', 'actif'], name='lims_delega_demande_9350fc_idx')],
                'unique_together': {('demande', 'role', 'utilisateur')},
            },
        ),
    ]
