# Generated by Django 5.2 on 2025-08-27 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_analyse_brut_saisi_le_analyse_brut_saisi_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DemandeEtatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['at', 'pk'],
            },
        ),
        migrations.RemoveIndex(
            model_name='demande',
            name='lims_demand_etat_985d99_idx',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='etat',
        ),
        migrations.AddField(
            model_name='demande',
            name='current_etat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_courantes', to='lims.demandeetat'),
        ),
        migrations.AddField(
            model_name='demandeetatentry',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeetatentry',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat_entries', to='lims.demande'),
        ),
        migrations.AddField(
            model_name='demandeetatentry',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='lims.demandeetat'),
        ),
        migrations.AddIndex(
            model_name='demandeetatentry',
            index=models.Index(fields=['demande', 'at'], name='lims_demand_demande_a94962_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeetatentry',
            index=models.Index(fields=['demande', 'etat'], name='lims_demand_demande_554ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeetatentry',
            index=models.Index(fields=['etat', 'at'], name='lims_demand_etat_id_c68f1c_idx'),
        ),
    ]
