# Generated by Django 5.2 on 2025-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_demandeetat_demandeetatentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='effectif_troupeau',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demande',
            name='nbre_animaux_malades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demande',
            name='nbre_animaux_morts',
            field=models.IntegerField(default=0),
        ),
    ]
