# Generated by Django 5.2 on 2025-08-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espece', '0006_alter_espece_user'),
        ('lims', '0010_demande_effectif_troupeau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echantillon',
            name='espece',
        ),
        migrations.AddField(
            model_name='demande',
            name='espece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Espece.espece'),
        ),
    ]
