# Generated by Django 5.2 on 2025-08-28 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lims', '0011_remove_echantillon_espece_demande_espece'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='resultat_schema',
            field=models.CharField(default='v1', max_length=20),
        ),
        migrations.AddField(
            model_name='analyse',
            name='resultat_source_format',
            field=models.CharField(blank=True, choices=[('json', 'JSON'), ('csv', 'CSV'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('pdf', 'PDF')], max_length=10),
        ),
        migrations.AddField(
            model_name='analyse',
            name='resultat_source_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analyse',
            name='resultat_source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='nom_original',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='taille_octets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='piecejointe',
            index=models.Index(fields=['content_type', 'object_id'], name='lims_piecej_content_fe90e4_idx'),
        ),
        migrations.AddIndex(
            model_name='piecejointe',
            index=models.Index(fields=['type'], name='lims_piecej_type_f3c919_idx'),
        ),
    ]
