# Generated by Django 5.2 on 2025-08-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_analyse_resultat_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='interpretation',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='resultat_brut',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='resultat_schema',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='resultat_source_format',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='resultat_source_meta',
        ),
        migrations.RemoveField(
            model_name='analyse',
            name='resultat_source_text',
        ),
    ]
