# Generated by Django 5.2 on 2025-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_remove_analyse_interpretation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='code_echantillon',
            field=models.CharField(max_length=40),
        ),
    ]
