# Generated by Django 5.2 on 2025-08-30 13:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_alter_echantillon_code_echantillon'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='conformite',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme')], default='conforme', max_length=20),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='envoi_externe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echantillon',
            name='reception_externe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcatalogue',
            name='tarif_fcfa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarif unitaire du test en FCFA', max_digits=12),
        ),
    ]
