# Generated by Django 5.2 on 2025-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_echantillon_conformite_echantillon_envoi_externe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcatalogue',
            name='section',
            field=models.CharField(choices=[('APBH', 'Anatomie pathologie et Biochimie hématologie'), ('BACP', 'Bactériologie et parasitologie'), ('HQA', 'Hygiène et qualité des aliments'), ('VIRO', 'Virologie'), ('CQVMV', 'Contrôle qualité des vaccins et des médicaments vétérinaires'), ('SMAV', 'Service des maladies animales à vecteurs')], max_length=20),
        ),
    ]
