# Generated by Django 5.2 on 2025-09-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_alter_testcatalogue_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='id_animal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
