# Generated by Django 5.2 on 2025-09-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espece', '0006_alter_espece_user'),
        ('lims', '0017_alter_echantillon_id_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='espece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Espece.espece'),
        ),
    ]
