# Generated by Django 5.1.7 on 2025-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Foyer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foyer",
            name="resultats_labo",
        ),
        migrations.AddField(
            model_name="foyer",
            name="resultats_nonconformes",
            field=models.CharField(
                choices=[("OUI", "Oui"), ("NON", "Non")], default="NON", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="foyer",
            name="absence_reactifs",
            field=models.CharField(
                choices=[("OUI", "Oui"), ("NON", "Non")], default="NON", max_length=3
            ),
        ),
    ]
