# Generated by Django 5.1.7 on 2025-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foyer', '0002_remove_foyer_resultats_labo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foyer',
            old_name='recommandations_suivi',
            new_name='recommandations',
        ),
        migrations.RemoveField(
            model_name='foyer',
            name='resultats_nonconformes',
        ),
    ]
