# Generated by Django 5.1.7 on 2025-05-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foyer', '0003_rename_recommandations_suivi_foyer_recommandations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foyer',
            name='absence_reactifs',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='OUI', max_length=3),
        ),
    ]
