# Generated by Django 5.2 on 2025-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foyer', '0005_directionsv_ministere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foyer',
            name='nbre_echant_nonconforme',
        ),
        migrations.RemoveField(
            model_name='foyer',
            name='nbre_echant_positif',
        ),
        migrations.AddField(
            model_name='foyer',
            name='date_signalement',
            field=models.DateField(blank=True, help_text='Date à laquelle le foyer a été signalé', null=True),
        ),
        migrations.AddField(
            model_name='foyer',
            name='notification_envoyee',
            field=models.BooleanField(default=False, help_text='Indique si la notification e-mail a déjà été envoyée.'),
        ),
        migrations.AddField(
            model_name='foyer',
            name='resultat_analyse',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('negatif', 'Négatif'), ('douteux', 'Douteux')], help_text='Positif / Négatif / Douteux', max_length=8, null=True),
        ),
    ]
