# Generated by Django 5.2 on 2025-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foyer', '0006_remove_foyer_nbre_echant_nonconforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foyer',
            name='date_rapportage',
            field=models.DateField(null=True),
        ),
    ]
