# Generated by Django 5.2 on 2025-05-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commune', '0003_alter_commune_user'),
        ('Departement', '0003_alter_departement_user'),
        ('Region', '0002_region_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInspecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observations_generales', models.TextField(blank=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection_medicaments.agentinspecteur')),
            ],
        ),
        migrations.CreateModel(
            name='GestionDechetsBiomedicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_gestion', models.CharField(choices=[('jeter___la_poubelle', 'Jeter à la Poubelle'), ('enfouissement', 'Enfouissement'), ('incin_ration', 'Incinération'), ('recyclage', 'Recyclage'), ('autres', 'Autres')], max_length=30)),
                ('autre_type', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.inspectionetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionLocaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separation_locaux', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('quai_debarquement', models.CharField(choices=[('existe', 'Existe'), ('absente', 'Absente')], max_length=10)),
                ('magasins_stockage', models.CharField(choices=[('existe', 'Existe'), ('absente', 'Absente')], max_length=10)),
                ('zone_stockage_retir', models.CharField(choices=[('existe', 'Existe'), ('absente', 'Absente')], max_length=10)),
                ('chambre_froide', models.CharField(choices=[('existente', 'Existente'), ('absente', 'Absente')], max_length=10)),
                ('source_energie', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('vehicule_transport', models.CharField(choices=[('existente', 'Existente'), ('absente', 'Absente')], max_length=10)),
                ('rayonnage', models.CharField(choices=[('existentes', 'Existentes')], max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.inspectionetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='ControleDocumentaireDetaillant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisation_exercer', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('nombre_personnel', models.IntegerField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True)),
                ('observations_personnel', models.TextField(blank=True)),
                ('sources_approvisionnement', models.TextField(blank=True)),
                ('registre_ventes_mv', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('observations_registres', models.TextField(blank=True)),
                ('enseigne', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('observations_enseigne', models.TextField(blank=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.inspectionetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsDelivrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente_mv', models.CharField(choices=[('sur_ordonnance', 'Sur ordonnance'), ('sans_ordonnance', 'Sans ordonnance'), ('les_deux', 'Les deux')], max_length=30)),
                ('observations_vente', models.TextField(blank=True)),
                ('au_detail', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('observations_detail', models.TextField(blank=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.inspectionetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_liste_clients', models.CharField(choices=[('fait', 'Fait'), ('non_pas_fait', 'Non fait')], max_length=20)),
                ('respect_fefo', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('enregistrement_automatique', models.CharField(choices=[('fait', 'Fait'), ('non_pas_fait', 'Non fait')], max_length=20)),
                ('respect_transport', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.inspectionetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='StructureVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_structure', models.CharField(choices=[('GROSSISTE', 'Grossiste'), ('Detaillant', 'Détaillant')], max_length=50)),
                ('gps', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Commune.commune')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Departement.departement')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Region.region')),
            ],
        ),
        migrations.AddField(
            model_name='inspectionetablissement',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.structurevente'),
        ),
        migrations.CreateModel(
            name='VerificationPhysiqueProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amm', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('observations_amm', models.TextField(blank=True)),
                ('date_peremption', models.CharField(choices=[('valide', 'Valide'), ('non_valide', 'Non valide')], max_length=10)),
                ('depuis_quand', models.DateField(blank=True, null=True)),
                ('composition', models.TextField(blank=True)),
                ('date_ouverture_flacon', models.CharField(choices=[('mentionn_e', 'Mentionnée'), ('non_mentionn_e', 'Non mentionnée')], max_length=30)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('contenant', models.TextField(blank=True)),
                ('conditionnement', models.TextField(blank=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection_medicaments.inspectionetablissement')),
            ],
        ),
    ]
