# Generated by Django 5.2 on 2025-05-19 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinspecteur',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentinspecteur',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentinspecteur',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinspecteur',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentinspecteur',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conditionsdelivrance',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditionsdelivrance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditionsdelivrance',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionsdelivrance',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conditionsdelivrance',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='controledocumentairedetaillant',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controledocumentairedetaillant',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controledocumentairedetaillant',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controledocumentairedetaillant',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='controledocumentairedetaillant',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='descriptionlocaux',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='descriptionlocaux',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descriptionlocaux',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptionlocaux',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='descriptionlocaux',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gestiondechetsbiomedicaux',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestiondechetsbiomedicaux',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestiondechetsbiomedicaux',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestiondechetsbiomedicaux',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gestiondechetsbiomedicaux',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspectionetablissement',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionetablissement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionetablissement',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionetablissement',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspectionetablissement',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operationsdistribution',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationsdistribution',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationsdistribution',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationsdistribution',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationsdistribution',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='structurevente',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structurevente',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurevente',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structurevente',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structurevente',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='verificationphysiqueproduits',
            name='chiffre_kbt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationphysiqueproduits',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationphysiqueproduits',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationphysiqueproduits',
            name='idkobo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationphysiqueproduits',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
