# Generated by Django 4.2 on 2025-09-06 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kobo_bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetLogical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kobo_bridge.kobosource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WideRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dims', models.JSONField(blank=True, default=dict)),
                ('meas', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widerows', to='semantic_layer.datasetlogical')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kobo_bridge.kobosource')),
            ],
            options={
                'ordering': ['-submitted_at', 'dataset'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=255)),
                ('transform', models.CharField(blank=True, max_length=80, null=True)),
                ('transform_params', models.JSONField(blank=True, default=dict)),
                ('default_agg', models.CharField(choices=[('sum', 'sum'), ('count', 'count'), ('avg', 'avg'), ('min', 'min'), ('max', 'max')], default='sum', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='semantic_layer.datasetlogical')),
            ],
            options={
                'ordering': ['dataset', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FilterDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('dim_code', models.CharField(max_length=80)),
                ('op', models.CharField(choices=[('in', 'IN (liste)'), ('eq', 'Égal'), ('between', 'Entre (dates/nombres)'), ('gte', '>= (min)'), ('lte', '<= (max)'), ('contains', 'Contient (texte)')], default='in', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='semantic_layer.datasetlogical')),
            ],
            options={
                'ordering': ['dataset', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=255)),
                ('dtype', models.CharField(choices=[('text', 'Texte'), ('date', 'Date'), ('code', 'Code'), ('geo', 'Géographie')], default='text', max_length=20)),
                ('transform', models.CharField(blank=True, max_length=80, null=True)),
                ('transform_params', models.JSONField(blank=True, default=dict)),
                ('is_time', models.BooleanField(default=False)),
                ('is_geo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='semantic_layer.datasetlogical')),
            ],
            options={
                'ordering': ['dataset', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='widerow',
            index=models.Index(fields=['dataset', 'submitted_at'], name='semantic_la_dataset_9bf08d_idx'),
        ),
        migrations.AddIndex(
            model_name='widerow',
            index=models.Index(fields=['dataset', 'instance_id'], name='semantic_la_dataset_c0e995_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='widerow',
            unique_together={('dataset', 'instance_id')},
        ),
        migrations.AddIndex(
            model_name='measure',
            index=models.Index(fields=['dataset', 'code'], name='semantic_la_dataset_a9ac5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together={('dataset', 'code')},
        ),
        migrations.AddIndex(
            model_name='filterdef',
            index=models.Index(fields=['dataset', 'code'], name='semantic_la_dataset_9b5074_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filterdef',
            unique_together={('dataset', 'code')},
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['dataset', 'code'], name='semantic_la_dataset_124125_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('dataset', 'code')},
        ),
    ]
