# Generated by Django 5.0.3 on 2024-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("LOI", "Loi"),
                            ("REGLEMENTATION_NATIONALE", "Réglementation nationale"),
                            (
                                "REGLEMENTATION_INTERNATIONALE",
                                "Réglementation internationale",
                            ),
                            ("ARRETE_MINISTERIEL", "Arrêté ministériel"),
                            ("DIRECTIVE", "Directive"),
                            ("GUIDELINE", "Ligne directrice"),
                            ("CIRCULAIRE", "Circulaire"),
                            ("PROCEDURE", "Procédure"),
                            ("Memo", "Memo"),
                            ("Note", "Note"),
                            ("Lettre", "Lettre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("date_de_mise_en_application", models.DateField()),
                ("autorite_emission", models.CharField(max_length=255)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
        ),
    ]
