# Generated by Django 5.0.3 on 2024-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Document", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["date_de_mise_en_application"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="date_de_publication",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="mots_cles",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="valide",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("LOI", "Loi"),
                    ("REGLEMENTATION_NATIONALE", "Réglementation nationale"),
                    ("REGLEMENTATION_INTERNATIONALE", "Réglementation internationale"),
                    ("ARRETE_MINISTERIEL", "Arrêté ministériel"),
                    ("DECRET", "Decret"),
                    ("DIRECTIVE", "Directive"),
                    ("GUIDELINE", "Ligne directrice"),
                    ("CIRCULAIRE", "Circulaire"),
                    ("PROCEDURE", "Procédure"),
                    ("MEMO", "Mémo"),
                    ("NORME", "Norme"),
                    ("NOTE", "Note"),
                    ("LETTRE", "Lettre"),
                    ("REGLEMENTATION_REGIONALE", "Réglementation régionale"),
                    ("POLITIQUE", "Politique"),
                    ("ETUDE", "Étude"),
                ],
                max_length=50,
            ),
        ),
    ]
