# Generated by Django 5.0.3 on 2025-01-31 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Commune", "0001_initial"),
        ("Departement", "0001_initial"),
        ("Region", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Titre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DETACHE", "Détaché"),
                            ("STAGE", "Position de stage"),
                            ("DISPONIBILITE", "Disponibilité"),
                            ("DECDE", "Décédé"),
                            ("RETRAITE", "Retraité"),
                        ],
                        default="IMPORTATION",
                        max_length=50,
                    ),
                ),
                ("nbre", models.IntegerField()),
                ("annee", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Commune.commune",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Departement.departement",
                    ),
                ),
                (
                    "entite_administrative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personnel.entite",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Region.region"
                    ),
                ),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personnel.titre",
                    ),
                ),
            ],
        ),
    ]
