# Generated by Django 5.0.3 on 2025-02-05 10:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Commune", "0003_alter_commune_user"),
        ("Departement", "0003_alter_departement_user"),
        ("Personnel", "0003_alter_personnel_user"),
        ("Region", "0002_region_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Commune.commune",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Departement.departement",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="nbre",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="position",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DETACHE", "Détaché"),
                    ("STAGE", "Position de stage"),
                    ("DISPONIBILITE", "Disponibilité"),
                    ("DECDE", "Décédé"),
                    ("RETRAITE", "Retraité"),
                ],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="personnel",
            index=models.Index(fields=["annee"], name="Personnel_p_annee_bdb07d_idx"),
        ),
        migrations.AddIndex(
            model_name="personnel",
            index=models.Index(
                fields=["region"], name="Personnel_p_region__0ed8a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnel",
            index=models.Index(
                fields=["position"], name="Personnel_p_positio_54a749_idx"
            ),
        ),
    ]
