# Generated by Django 5.2 on 2025-08-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureImportationVisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=100, unique=True, verbose_name='Numéro de la facture')),
                ('date_visa_dsv', models.DateField(auto_now_add=True, verbose_name='Date du visa DSV')),
                ('fichier_facture', models.FileField(upload_to='factures_visees/', verbose_name='Facture visée (PDF)')),
                ('est_visa_pif', models.BooleanField(default=False, verbose_name='Facture visée par le PIF ?')),
                ('date_visa_pif', models.DateTimeField(blank=True, null=True, verbose_name='Date visa PIF')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire PIF')),
                ('vise_par_dsv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_visees_dsv', to=settings.AUTH_USER_MODEL, verbose_name='Visa DSV par')),
                ('vise_par_pif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_visees_pif', to=settings.AUTH_USER_MODEL, verbose_name='Visa PIF par')),
            ],
            options={
                'verbose_name': 'Facture importation visée',
                'verbose_name_plural': 'Factures importation visées',
                'ordering': ['-date_visa_dsv'],
            },
        ),
    ]
