# Generated by Django 5.2 on 2025-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_importation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureimportationvisee',
            name='Structure',
            field=models.CharField(default='Inconnue', max_length=100, verbose_name='Nom de la structure'),
        ),
    ]
