# Generated by Django 5.1.7 on 2025-05-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireKobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('modele_django', models.CharField(max_length=100)),
                ('parser', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sync', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration_kobo.formulairekobo')),
            ],
        ),
    ]
