# Generated by Django 5.1.7 on 2025-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_kobo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairekobo',
            name='base_url',
            field=models.URLField(default='https://kf.kobotoolbox.org'),
        ),
        migrations.AddField(
            model_name='formulairekobo',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='formulairekobo',
            name='modele_django',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formulairekobo',
            name='parser',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='formulairekobo',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
