# Generated by Django 5.0.3 on 2025-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Année", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="année",
            name="annee",
            field=models.IntegerField(
                choices=[
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                ]
            ),
        ),
    ]
