# Generated by Django 5.0.3 on 2024-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laboratoire",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("laboratoire", models.CharField(max_length=100)),
            ],
        ),
    ]
