# Generated by Django 5.0.3 on 2024-08-28 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Année", "0001_initial"),
        ("Commune", "0001_initial"),
        ("Departement", "0001_initial"),
        ("Espece", "0001_initial"),
        ("Region", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Effectif",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Effectif", models.IntegerField()),
                (
                    "Annee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Année.année"
                    ),
                ),
                (
                    "Commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Commune.commune",
                    ),
                ),
                (
                    "Departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Departement.departement",
                    ),
                ),
                (
                    "Espece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Espece.espece"
                    ),
                ),
                (
                    "Region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Region.region"
                    ),
                ),
            ],
        ),
    ]
