# Generated by Django 5.1.7 on 2025-04-15 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commune', '0003_alter_commune_user'),
        ('Departement', '0003_alter_departement_user'),
        ('Region', '0002_region_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_proprietaire', models.CharField(choices=[('PUBLIQUE', 'Publique'), ('PRIVEE', 'Privée')], default='PUBLIQUE', max_length=10)),
                ('nom_proprietaire', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_proprietaire', models.CharField(blank=True, max_length=100, null=True)),
                ('autorisation_ouverture', models.BooleanField(default=False)),
                ('document_autorisation', models.FileField(blank=True, null=True, upload_to='docs/autorisations/')),
                ('etat_initial', models.CharField(choices=[('CONSTRUCTION', 'En construction'), ('REHABILITATION', 'En réhabilitation'), ('FONCTIONNEL', 'Fonctionnel'), ('NON_FONCTIONNEL', 'Non fonctionnel'), ('MAUVAIS', 'Mauvais')], max_length=30)),
                ('niveau_priorite', models.CharField(choices=[('BAS', 'Bas'), ('MOYEN', 'Moyen'), ('HAUT', 'Élevé')], default='MOYEN', max_length=10)),
                ('localite', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_construction', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='infrastructures_photos/')),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='infrastructures_docs/')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Infrastructure.typeinfrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inspection', models.DateField()),
                ('inspecteur', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('etat_derniere_inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_precedent_inspection', to='Infrastructure.etatinfrastructure')),
                ('etat_inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_courant_inspection', to='Infrastructure.etatinfrastructure')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='Infrastructure.infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueEtatInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('etat_inspection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Infrastructure.etatinfrastructure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Infrastructure.infrastructure')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_etats', to='Infrastructure.inspection')),
            ],
        ),
    ]
