# Generated by Django 5.1.7 on 2025-04-15 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='type_financement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Infrastructure.typefinancement'),
        ),
    ]
