# Generated by Django 5.1.7 on 2025-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0002_typefinancement_infrastructure_type_financement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='niveau_priorite',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='etat_initial',
            field=models.CharField(choices=[('CONSTRUCTION', 'En construction'), ('REHABILITATION', 'En réhabilitation'), ('FONCTIONNEL', 'Fonctionnel'), ('NON_FONCTIONNEL', 'Non fonctionnel')], max_length=30),
        ),
    ]
