# Generated by Django 5.1.7 on 2025-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0003_remove_infrastructure_niveau_priorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='adresse_proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='date_naissance_proprietaire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='email_proprietaire',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='numero_piece_identite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='piece_identite_proprietaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='sexe_proprietaire',
            field=models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='telephone_proprietaire',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
