# Generated by Django 5.1.7 on 2025-04-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infrastructure', '0004_infrastructure_adresse_proprietaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='document_justificatif',
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='etat_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etat_initial', to='Infrastructure.etatinfrastructure'),
        ),
    ]
