# Generated by Django 5.2 on 2025-08-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Region', '0002_region_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Type de matériel',
                'verbose_name_plural': 'Types de matériel',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Dotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('date_dotation', models.DateField(verbose_name='Date de dotation')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='dotations/pjs/', verbose_name='Pièce jointe (bon/PV)')),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotations_materiel', to='Region.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotations', to='materiel.typemateriel')),
            ],
            options={
                'verbose_name': 'Dotation de matériel',
                'verbose_name_plural': 'Dotations de matériel',
                'ordering': ['-date_dotation', 'region__Nom', 'type_materiel__nom'],
                'indexes': [models.Index(fields=['region'], name='materiel_do_region__7af0c0_idx'), models.Index(fields=['type_materiel'], name='materiel_do_type_ma_38ce3d_idx'), models.Index(fields=['date_dotation'], name='materiel_do_date_do_4b013d_idx')],
                'unique_together': {('type_materiel', 'region', 'date_dotation')},
            },
        ),
    ]
