# Generated by Django 5.2 on 2025-08-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0008_alter_campagne_type_campagne'),
        ('Region', '0002_region_user'),
        ('materiel', '0001_seed_types_materiel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotation',
            options={'ordering': ['-date_dotation', 'campagne__Campagne', 'region__Nom', 'type_materiel__nom'], 'verbose_name': 'Dotation de matériel', 'verbose_name_plural': 'Dotations de matériel'},
        ),
        migrations.AlterUniqueTogether(
            name='dotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dotation',
            name='campagne',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dotations', to='Campagne.campagne'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotations_materiel', to='Region.region'),
        ),
        migrations.AlterUniqueTogether(
            name='dotation',
            unique_together={('type_materiel', 'region', 'campagne', 'date_dotation')},
        ),
        migrations.AddIndex(
            model_name='dotation',
            index=models.Index(fields=['campagne'], name='materiel_do_campagn_07b1fc_idx'),
        ),
    ]
