# Generated by Django 5.2 on 2025-08-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0008_alter_campagne_type_campagne'),
        ('materiel', '0002_alter_dotation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotation',
            name='campagne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dotations', to='Campagne.campagne'),
        ),
    ]
