# Generated by Django 5.2 on 2025-08-11 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0008_alter_campagne_type_campagne'),
        ('Maladie', '0006_alter_maladie_user'),
        ('materiel', '0003_alter_dotation_campagne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DotationDoseVaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_doses', models.PositiveIntegerField(default=0, verbose_name='Quantité (doses)')),
                ('date_dotation', models.DateField(verbose_name='Date de dotation')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='dotations_doses/pjs/', verbose_name='Pièce jointe (bon/PV)')),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotations_doses', to='Campagne.campagne')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotations_doses', to='Maladie.maladie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dotation en doses de vaccin',
                'verbose_name_plural': 'Dotations en doses de vaccin',
                'ordering': ['-date_dotation', 'campagne__Campagne', 'maladie__Maladie'],
                'indexes': [models.Index(fields=['campagne'], name='materiel_do_campagn_7c1b43_idx'), models.Index(fields=['maladie'], name='materiel_do_maladie_315d63_idx'), models.Index(fields=['date_dotation'], name='materiel_do_date_do_408916_idx')],
                'unique_together': {('campagne', 'maladie', 'date_dotation')},
            },
        ),
    ]
