# Generated by Django 5.0.3 on 2024-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Maladie", models.CharField(max_length=200)),
                (
                    "Type",
                    models.CharField(
                        choices=[("Animale", "Animale"), ("Zoonotique", "Zoonotique")],
                        default="Animale",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
