# Generated by Django 5.0.3 on 2024-10-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Espece", "0001_initial"),
        ("Maladie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maladie",
            name="Espece",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Espece.espece",
            ),
            preserve_default=False,
        ),
    ]
