# Generated by Django 5.0.3 on 2024-10-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Espece", "0002_alter_espece_espece"),
        ("Maladie", "0002_maladie_espece"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maladie",
            name="Espece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maladies",
                to="Espece.espece",
            ),
        ),
    ]
