# Generated by Django 5.0.3 on 2024-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Espece", "0004_alter_espece_espece"),
        ("Maladie", "0003_alter_maladie_espece"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maladie",
            name="Espece",
        ),
        migrations.AddField(
            model_name="maladie",
            name="Espece",
            field=models.ManyToManyField(related_name="maladies", to="Espece.espece"),
        ),
    ]
