# Generated by Django 5.2 on 2025-08-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinataireAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom du destinataire', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True, help_text='Cocher pour recevoir les alertes')),
            ],
        ),
    ]
