# Generated by Django 5.2 on 2025-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatairealerte',
            name='formulaire',
            field=models.CharField(blank=True, help_text='Nom du formulaire', max_length=100, null=True),
        ),
    ]
