# Generated by Django 5.2 on 2025-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_destinatairealerte_formulaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatairealerte',
            name='formulaire',
            field=models.CharField(blank=True, choices=[('Vaccination', 'Vaccination'), ('Rapportage', 'Rapportage')], default='Vaccination', help_text='Nom du formulaire', max_length=100, null=True, verbose_name='formulaire'),
        ),
    ]
