# Generated by Django 4.2 on 2025-09-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semantic_layer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('default_group_dims', models.JSONField(default=list)),
                ('default_metrics', models.JSONField(default=list)),
                ('visible_filters', models.JSONField(default=list)),
                ('computed_metrics', models.JSONField(blank=True, default=list, help_text='Cache de métriques calculées à partir de la config. Toujours non nul.')),
                ('menu_title', models.CharField(default='', max_length=120)),
                ('menu_icon', models.CharField(default='bi-graph-up', max_length=50)),
                ('materialized_name', models.CharField(blank=True, max_length=128, null=True)),
                ('materialized_last_refresh', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='semantic_layer.datasetlogical')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='WidgetDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_idx', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='publishing.datasetview')),
            ],
            options={
                'ordering': ('order_idx', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExportDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('format', models.CharField(max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('filename_pattern', models.CharField(default='AHIS_{slug}_{date}', max_length=200)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='publishing.datasetview')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
