# Generated by Django 4.2 on 2025-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetview',
            name='table_hidden_cols',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='datasetview',
            name='table_only_cols',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
