# Generated by Django 4.2 on 2025-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_datasetview_table_hidden_cols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetview',
            name='default_group_dims',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='datasetview',
            name='default_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='datasetview',
            name='visible_filters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exportdef',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='widgetdef',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
