# Generated by Django 4.2 on 2025-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_alter_datasetview_default_group_dims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdef',
            name='format',
            field=models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx')], max_length=10),
        ),
        migrations.AlterField(
            model_name='widgetdef',
            name='type',
            field=models.CharField(choices=[('table', 'table'), ('line', 'line'), ('bar', 'bar'), ('pie', 'pie'), ('kpi_card', 'kpi_card'), ('kpi', 'kpi'), ('map', 'map')], max_length=30),
        ),
    ]
