# Generated by Django 5.1.6 on 2025-03-10 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="direction_generale",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="direction_technique",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="sous_direction",
        ),
    ]
