# Generated by Django 5.1.6 on 2025-03-10 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_resources", "0002_remove_employe_direction_generale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="delegation",
        ),
        migrations.RemoveField(
            model_name="employe",
            name="secteur",
        ),
    ]
