# Generated by Django 5.1.6 on 2025-03-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_resources", "0003_remove_employe_delegation_remove_employe_secteur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="statut",
        ),
        migrations.AddField(
            model_name="employe",
            name="position",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DETACHE", "Détaché"),
                    ("STAGE", "Position de stage"),
                    ("DISPONIBILITE", "Disponibilité"),
                    ("DECDE", "Décédé"),
                    ("RETRAITE", "Retraité"),
                ],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="sexe",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Féminin")],
                default="M",
                max_length=50,
            ),
        ),
    ]
