# Generated by Django 5.1.6 on 2025-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_resources", "0004_remove_employe_statut_employe_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="matricule",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
