# Generated by Django 5.0.3 on 2024-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Espece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Espece",
                    models.CharField(
                        choices=[
                            ("Bovins", "Bovins"),
                            ("Ovins", "Ovins"),
                            ("Caprins", "Caprins"),
                            ("Camelidés", "Camelidés"),
                            ("Équins", "Équins"),
                            ("Porcins", "Porcins"),
                            ("Volaille", "Volaille"),
                            ("Espèces aquatiques", "Espèces aquatiques"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
