# Generated by Django 5.0.3 on 2024-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Espece", "0002_alter_espece_espece"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espece",
            name="Espece",
            field=models.CharField(
                choices=[
                    ("Bovins", "Bovins"),
                    ("Ovins+Caprins", "Ovins+Caprins"),
                    ("Camelidés", "Camelidés"),
                    ("Équins", "Équins"),
                    ("Porcins", "Porcins"),
                    ("Volaille", "Volaille"),
                    ("Canins", "Canins"),
                    ("Espèces aquatiques", "Espèces aquatiques"),
                ],
                max_length=50,
            ),
        ),
    ]
