# Generated by Django 5.2 on 2025-07-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaysMonde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='aibd.continent')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVeterinaireAIBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_operation', models.CharField(choices=[('importation', 'Importation'), ('exportation', 'Exportation')], max_length=20, verbose_name="Type d'opération")),
                ('expediteur', models.CharField(max_length=255, verbose_name='Expéditeur/Importateur')),
                ('lta', models.CharField(blank=True, max_length=100, null=True, verbose_name='LTA')),
                ('type_produit', models.CharField(choices=[('Animaux', 'Animaux'), ('POD', 'POD'), ('Medicaments', 'Médicaments')], max_length=20, verbose_name='Type de produit')),
                ('produit', models.CharField(max_length=100, verbose_name='Produit')),
                ('quantite', models.FloatField(verbose_name='Quantité / Nombre')),
                ('numero_vol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de vol')),
                ('date_vol', models.DateField(blank=True, null=True, verbose_name='Date de vol')),
                ('societe_transit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Société de transit')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aibd.continent', verbose_name='Continent')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aibd.paysmonde', verbose_name='Pays')),
            ],
        ),
    ]
