# Generated by Django 5.2 on 2025-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aibd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceveterinaireaibd',
            name='Idkobo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID kobo'),
        ),
    ]
