# Generated by Django 5.0.3 on 2024-08-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Espece", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeplacementAnimaux",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nbre_animaux", models.IntegerField()),
                (
                    "numero_certificat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "autorite_delivrance_certificat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "duree_validite_certificat",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "copie_certificat",
                    models.FileField(blank=True, null=True, upload_to="certificats/"),
                ),
                ("provenance", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date_deplacement", models.DateField()),
                (
                    "mode_de_transport",
                    models.CharField(
                        choices=[
                            ("ROUTE", "Route"),
                            ("AIR", "Air"),
                            ("MER", "Mer"),
                            ("RAIL", "Rail"),
                        ],
                        default="ROUTE",
                        max_length=50,
                    ),
                ),
                ("raison_deplacement", models.TextField(blank=True, null=True)),
                (
                    "origine_etablissement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "destination_etablissement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("duree_deplacement", models.IntegerField(blank=True, null=True)),
                (
                    "nom_transporteur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_transporteur",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "espece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Espece.espece"
                    ),
                ),
            ],
        ),
    ]
