# Generated by Django 5.0.3 on 2025-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DeplacementAnimaux", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deplacementanimaux",
            old_name="destination_etablissement",
            new_name="origine",
        ),
        migrations.RenameField(
            model_name="deplacementanimaux",
            old_name="origine_etablissement",
            new_name="proprietaire",
        ),
        migrations.AddField(
            model_name="deplacementanimaux",
            name="contact_proprietaire",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deplacementanimaux",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
