# Generated by Django 5.2 on 2025-05-11 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commune', '0003_alter_commune_user'),
        ('Departement', '0003_alter_departement_user'),
        ('DeplacementAnimaux', '0004_alter_deplacementanimaux_user'),
        ('Espece', '0006_alter_espece_user'),
        ('Maladie', '0006_alter_maladie_user'),
        ('Region', '0002_region_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeplacementAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animaux', models.PositiveIntegerField(verbose_name='Nombre d’animaux')),
                ('etablissement_origine', models.CharField(blank=True, max_length=255, null=True, verbose_name="Établissement d'origine")),
                ('etablissement_destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Établissement de destination')),
                ('date_deplacement', models.DateField(verbose_name='Date effective du déplacement')),
                ('duree_deplacement', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée du déplacement (en jours)')),
                ('mode_transport', models.CharField(choices=[('ROUTE', 'Route'), ('AIR', 'Air'), ('MER', 'Mer'), ('RAIL', 'Rail')], default='ROUTE', max_length=10, verbose_name='Mode de transport')),
                ('raison_deplacement', models.TextField(blank=True, null=True, verbose_name='Motif du déplacement')),
                ('numero_certificat', models.CharField(max_length=100, verbose_name='N° du certificat')),
                ('date_certificat', models.DateField(verbose_name='Date de délivrance du certificat')),
                ('fichier_certificat', models.FileField(blank=True, null=True, upload_to='certificats/', verbose_name='Copie du certificat')),
                ('nom_proprietaire', models.CharField(max_length=255, verbose_name='Nom du propriétaire')),
                ('contact_proprietaire', models.CharField(max_length=20, verbose_name='Téléphone du propriétaire')),
                ('nom_transporteur', models.CharField(blank=True, max_length=255, verbose_name='Nom du transporteur')),
                ('contact_transporteur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du transporteur')),
                ('maladie_detectee', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='NON', max_length=3, verbose_name='Y a-t-il une maladie suspectée ?')),
                ('nombre_animaux_malades', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre d’animaux malades')),
                ('nombre_animaux_traites', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre d’animaux traités')),
                ('nombre_animaux_vaccines', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre d’animaux vaccinés')),
                ('nombre_animaux_quarantaine', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre d’animaux mis en quarantaine')),
                ('mesures_prises', models.TextField(blank=True, help_text='Autres actions : désinfection, isolement, alerte sanitaire...', null=True, verbose_name='Mesures de gestion sanitaire')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('commune_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deplacement_entree', to='Commune.commune')),
                ('commune_provenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deplacement_sortie', to='Commune.commune')),
                ('departement_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deplacement_entree', to='Departement.departement')),
                ('departement_provenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deplacement_sortie', to='Departement.departement')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Espece.espece', verbose_name='Espèce concernée')),
                ('maladie_suspectee', models.ForeignKey(blank=True, help_text='Sélectionner la maladie suspectée ou détectée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Maladie.maladie', verbose_name='Maladie suspectée / constatée')),
                ('region_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deplacement_entree', to='Region.region')),
                ('region_provenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deplacement_sortie', to='Region.region')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Déplacement d’animaux',
                'verbose_name_plural': 'Déplacements d’animaux',
                'ordering': ['-date_deplacement'],
            },
        ),
        migrations.DeleteModel(
            name='DeplacementAnimaux',
        ),
    ]
