# Generated by Django 5.2 on 2025-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeplacementAnimaux', '0005_deplacementanimal_delete_deplacementanimaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='deplacementanimal',
            name='latitude_poste_controle',
            field=models.FloatField(blank=True, help_text='Coordonnée latitude du poste de contrôle (ex: 13.51234)', null=True, verbose_name='Latitude du poste de contrôle'),
        ),
        migrations.AddField(
            model_name='deplacementanimal',
            name='longitude_poste_controle',
            field=models.FloatField(blank=True, help_text='Coordonnée longitude du poste de contrôle (ex: 2.13245)', null=True, verbose_name='Longitude du poste de contrôle'),
        ),
    ]
