# Generated by Django 5.2 on 2025-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeplacementAnimaux', '0006_deplacementanimal_latitude_poste_controle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deplacementanimal',
            name='date_certificat',
        ),
        migrations.RemoveField(
            model_name='deplacementanimal',
            name='fichier_certificat',
        ),
        migrations.RemoveField(
            model_name='deplacementanimal',
            name='numero_certificat',
        ),
        migrations.AddField(
            model_name='deplacementanimal',
            name='nombre_certificats_vaccination_controles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Certificats de vaccination contrôlés'),
        ),
        migrations.AddField(
            model_name='deplacementanimal',
            name='nombre_certificats_vaccination_delivres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Certificats de vaccination délivrés'),
        ),
        migrations.AddField(
            model_name='deplacementanimal',
            name='nombre_laisser_passer_controles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Laisser-passer contrôlés'),
        ),
        migrations.AddField(
            model_name='deplacementanimal',
            name='nombre_laisser_passer_delivres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Laisser-passer délivrés'),
        ),
    ]
