# Generated by Django 5.2 on 2025-08-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('xform_id_string', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('slug', models.SlugField(help_text="Nom d'app: generated_apps/<slug>", unique=True)),
                ('secret_token', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('models', 'MODELS'), ('jsonb', 'JSONB')], default='models', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('parser_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='KoboFieldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_name', models.CharField(max_length=255)),
                ('model_field', models.CharField(max_length=255)),
                ('dtype', models.CharField(help_text='string|integer|decimal|date|datetime|select|geo|image|file|boolean', max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kobo_integration.koboform')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('IMPORTED', 'IMPORTED'), ('SKIPPED', 'SKIPPED'), ('FAILED', 'FAILED')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kobo_integration.koboform')),
            ],
            options={
                'indexes': [models.Index(fields=['instance_id'], name='kobo_integr_instanc_badf30_idx')],
            },
        ),
    ]
