# Generated by Django 5.2 on 2025-08-16 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_base', models.URLField(default='https://form.santeanimalechad.org')),
                ('api_token', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connexion Kobo',
                'verbose_name_plural': 'Connexions Kobo',
            },
        ),
    ]
