# Generated by Django 5.2 on 2025-08-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_integration', '0002_koboconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kobofieldmap',
            options={'ordering': ('form_id', 'id')},
        ),
        migrations.AlterModelOptions(
            name='koboform',
            options={'verbose_name': 'Kobo form', 'verbose_name_plural': 'Kobo forms'},
        ),
        migrations.AddField(
            model_name='koboform',
            name='api_base',
            field=models.URLField(blank=True, default='', help_text='(Optionnel) Prioritaire sur la connexion'),
        ),
        migrations.AddField(
            model_name='koboform',
            name='asset_uid',
            field=models.CharField(blank=True, help_text='UID du formulaire (aXXXX...) si connu', max_length=64),
        ),
        migrations.AddField(
            model_name='koboform',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Connexion Kobo à utiliser pour ce formulaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='kobo_integration.koboconnection'),
        ),
        migrations.AddField(
            model_name='koboform',
            name='field_catalog_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboform',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboform',
            name='sample_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koboform',
            name='schema_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='kobofieldmap',
            unique_together={('form', 'kobo_name')},
        ),
    ]
