# Generated by Django 5.2 on 2025-08-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_integration', '0003_alter_kobofieldmap_options_alter_koboform_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobofieldmap',
            name='dtype',
            field=models.CharField(help_text='string|integer|decimal|date|datetime|select|geo|image|file|boolean|json|repeat', max_length=64),
        ),
    ]
