# Generated by Django 5.1.7 on 2025-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0003_alter_campagne_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='statut',
            field=models.BooleanField(default=True),
        ),
    ]
