# Generated by Django 5.1.7 on 2025-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0004_campagne_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='type_campagne',
            field=models.CharField(choices=[('masse', 'Masse'), ('ciblee', 'Ciblée')], default='masse', max_length=10),
        ),
    ]
