# Generated by Django 5.1.7 on 2025-04-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0005_campagne_type_campagne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campagne',
            options={'verbose_name': 'Campagne', 'verbose_name_plural': 'Campagnes'},
        ),
        migrations.AlterUniqueTogether(
            name='campagne',
            unique_together={('Campagne', 'type_campagne')},
        ),
    ]
