# Generated by Django 5.1.7 on 2025-04-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Campagne", "0006_alter_campagne_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campagne",
            name="Campagne",
            field=models.CharField(
                max_length=100, verbose_name="Période de la campagne"
            ),
        ),
        migrations.AlterField(
            model_name="campagne",
            name="statut",
            field=models.BooleanField(default=True, verbose_name="Campagne active"),
        ),
        migrations.AlterField(
            model_name="campagne",
            name="type_campagne",
            field=models.CharField(
                choices=[("masse", "Masse"), ("ciblee", "Ciblée")],
                default="masse",
                max_length=10,
                verbose_name="Type de campagne",
            ),
        ),
    ]
