# Generated by Django 5.2 on 2025-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0007_alter_campagne_campagne_alter_campagne_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='type_campagne',
            field=models.CharField(choices=[('Masse', 'Masse'), ('Ciblee', 'Ciblée')], default='masse', max_length=10, verbose_name='Type de campagne'),
        ),
    ]
