# Generated by Django 5.2 on 2025-08-21 10:18

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campagne', '0008_alter_campagne_type_campagne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campagne',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='campagne',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='campagne',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('Campagne')), models.F('type_campagne'), name='uniq_campaign_type_ci_trimmed'),
        ),
    ]
