# Generated by Django 5.1.6 on 2025-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("type_document", models.CharField(max_length=255)),
                ("date_ajout", models.DateField(auto_now_add=True)),
                ("fichier", models.FileField(upload_to="documents_employes/")),
            ],
        ),
    ]
