# Generated by Django 5.1.6 on 2025-03-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "verbose_name": "Document Administratif",
                "verbose_name_plural": "Documents Administratifs",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="nom",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("contrat_travail", "Contrat de travail"),
                    ("certificat_travail", "Certificat de travail"),
                    ("certificat_competence", "Certificat de compétence"),
                    ("certificat_medical", "Certificat médical"),
                    ("rapport_evaluation", "Rapport d'évaluation de performance"),
                    ("rapport_formation", "Rapport de formation"),
                    ("fiche_paie", "Fiche de paie"),
                    ("demande_conge", "Demande de congé"),
                    ("approbation_conge", "Approbation de congé"),
                    ("releve_conge", "Relevé de congé"),
                    ("carte_identite", "Carte d'identité"),
                    ("passeport", "Passeport"),
                    ("permis_conduire", "Permis de conduire"),
                    ("attestation_formation", "Attestation de formation"),
                    ("certificat_participation", "Certificat de participation"),
                    ("attestation_affiliation", "Attestation d'affiliation"),
                    ("declaration_cotisations", "Déclaration de cotisations"),
                    ("declaration_impots", "Déclaration d'impôts"),
                    ("certificat_retenue_source", "Certificat de retenue à la source"),
                    ("avertissement", "Avertissement"),
                    ("sanction_disciplinaire", "Sanction disciplinaire"),
                    ("note_service", "Note de service"),
                    ("correspondance_officielle", "Correspondance officielle"),
                    ("autorisation_diverse", "Autorisation diverse"),
                    ("autre", "Autre"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
