# Generated by Django 5.1.6 on 2025-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("duree", models.IntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("approuvé", "Approuvé"),
                            ("en_attente", "En attente"),
                            ("refusé", "Refusé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarque", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TypeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
