# Generated by Django 5.1.6 on 2025-03-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gestion_absences", "0001_initial"),
        ("gestion_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conge",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_resources.employe",
            ),
        ),
        migrations.AddField(
            model_name="conge",
            name="type_conge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_absences.typeconge",
            ),
        ),
    ]
