# Generated by Django 5.1.6 on 2025-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_absences", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeconge",
            name="nombreJour",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="conge",
            name="duree",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="typeconge",
            name="nom",
            field=models.CharField(
                choices=[
                    ("maladie", "Maladie"),
                    ("annuel", "Annuel"),
                    ("maternite", "Maternité"),
                    ("paternite", "Paternité"),
                    ("parental", "Parental"),
                    ("sabbatique", "Sabbatique"),
                    ("evenement_familial", "Événement familial"),
                    ("formation", "Formation"),
                ],
                default="annuel",
                max_length=20,
            ),
        ),
    ]
