# Generated by Django 5.1.6 on 2025-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_absences", "0003_typeconge_nombrejour_alter_conge_duree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conge",
            name="solde",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
