# Generated by Django 5.1.7 on 2025-04-17 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commune', '0003_alter_commune_user'),
        ('Departement', '0003_alter_departement_user'),
        ('Espece', '0006_alter_espece_user'),
        ('Region', '0002_region_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionViande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abattoir', models.CharField(max_length=255)),
                ('date_inspection', models.DateField()),
                ('inspecteur', models.CharField(max_length=255)),
                ('numero_lot', models.CharField(max_length=100)),
                ('autre_espece', models.CharField(blank=True, max_length=255, null=True)),
                ('etat_animal', models.CharField(choices=[('bon', 'Bon'), ('suspect', 'Suspect'), ('mauvais', 'Mauvais')], max_length=20)),
                ('signes_anormaux', models.CharField(help_text='Signes cliniques observés, séparés par virgules', max_length=255)),
                ('autre_signe_anormal', models.CharField(blank=True, max_length=255, null=True)),
                ('aspect_carcasse', models.CharField(choices=[('normal', 'Normal'), ('decoloration', 'Décoloration'), ('lesions', 'Lésions visibles'), ('parasites', 'Parasites'), ('autre', 'Autre')], max_length=50)),
                ('poumons', models.CharField(choices=[('normal', 'Normal'), ('anomalie', 'Anomalie')], max_length=10)),
                ('foie', models.CharField(choices=[('normal', 'Normal'), ('anomalie', 'Anomalie')], max_length=10)),
                ('rate', models.CharField(choices=[('normal', 'Normal'), ('anomalie', 'Anomalie')], max_length=10)),
                ('coeur', models.CharField(choices=[('normal', 'Normal'), ('anomalie', 'Anomalie')], max_length=10)),
                ('description_anomalies', models.TextField(blank=True, null=True)),
                ('decision_sanitaire', models.CharField(choices=[('normal', 'Normal'), ('anomalie', 'Anomalie')], max_length=10)),
                ('observations', models.TextField(blank=True, null=True)),
                ('signature_inspecteur', models.CharField(blank=True, max_length=255, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espece.espece')),
            ],
        ),
        migrations.CreateModel(
            name='RegistreAbattage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ages', models.CharField(max_length=50)),
                ('sexes', models.CharField(max_length=10)),
                ('nombres', models.IntegerField()),
                ('poids', models.IntegerField(help_text='en kg')),
                ('valeur_financiere', models.IntegerField(help_text='en FCFA')),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espece.espece')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistreInspectionAnteMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalies', models.CharField(max_length=255)),
                ('symptomes', models.TextField()),
                ('nombres', models.IntegerField()),
                ('poids', models.IntegerField(help_text='en kg')),
                ('valeur_financiere', models.IntegerField(help_text='en FCFA')),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espece.espece')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistreSaisiesOrganes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organes_saisis', models.TextField()),
                ('motifs_saisies_organes', models.TextField()),
                ('nombres', models.IntegerField()),
                ('poids', models.IntegerField(help_text='en kg')),
                ('valeur_financiere', models.IntegerField(help_text='en FCFA')),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espece.espece')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistreSaisiesTotales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motifs_saisies', models.TextField()),
                ('nombres', models.IntegerField()),
                ('poids', models.IntegerField(help_text='en kg')),
                ('valeur_financiere', models.IntegerField(help_text='en FCFA')),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departement.departement')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espece.espece')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Region.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
