# Generated by Django 5.1.7 on 2025-04-17 13:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registreabattage',
            name='ages',
            field=models.CharField(choices=[('jeune', 'Jeunes'), ('adulte', 'Adultes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registreabattage',
            name='sexes',
            field=models.CharField(choices=[('males_entiens', 'Mâles entiers'), ('males_castres', 'Mâles castrés'), ('femelles', 'Femelles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registresaisiesorganes',
            name='motifs_saisies_organes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=1000),
        ),
        migrations.AlterField(
            model_name='registresaisiesorganes',
            name='organes_saisis',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=1000),
        ),
        migrations.AlterField(
            model_name='registresaisiestotales',
            name='motifs_saisies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=1000),
        ),
    ]
