# Generated by Django 5.1.7 on 2025-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0002_alter_registreabattage_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registreinspectionantemortem',
            name='symptomes',
            field=models.CharField(max_length=255),
        ),
    ]
