# Generated by Django 5.1.7 on 2025-04-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0003_alter_registreinspectionantemortem_symptomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registresaisiestotales',
            name='motifs_saisies',
            field=models.CharField(max_length=255),
        ),
    ]
