# Generated by Django 5.1.7 on 2025-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0004_alter_registresaisiestotales_motifs_saisies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registresaisiesorganes',
            name='motifs_saisies_organes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registresaisiesorganes',
            name='organes_saisis',
            field=models.CharField(max_length=255),
        ),
    ]
