# Generated by Django 5.1.7 on 2025-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0005_alter_registresaisiesorganes_motifs_saisies_organes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionviande',
            name='signes_anormaux',
            field=models.CharField(choices=[('fievre', 'Fièvre'), ('boiterie', 'Boiterie'), ('lesions_cutanees', 'Lésions cutanées'), ('signes_neuro', 'Signes neurologiques'), ('autres', 'Autres')], max_length=255),
        ),
    ]
