# Generated by Django 5.1.7 on 2025-04-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0006_alter_inspectionviande_signes_anormaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionviande',
            name='decision_sanitaire',
        ),
    ]
