# Generated by Django 5.1.7 on 2025-05-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante_publique', '0007_remove_inspectionviande_decision_sanitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionviande',
            name='autre_espece',
        ),
    ]
