# Generated by Django 5.0.3 on 2025-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KoboToolboxConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kobo_url", models.URLField()),
                ("token_form_vaccination", models.CharField(max_length=255)),
                ("uid_form_vaccination", models.CharField(max_length=255)),
                ("uid_form_surveillance", models.CharField(max_length=255)),
                ("token_form_surveillance", models.CharField(max_length=255)),
                ("uid_form_mobilite", models.CharField(max_length=255)),
                ("token_form_mobilite", models.CharField(max_length=255)),
                ("uid_form_infrastructure", models.CharField(max_length=255)),
                ("token_form_infrastructure", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
