# Generated by Django 5.0.3 on 2025-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_initialization", "0002_kobotoolboxconfig_user_logentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="object_id",
            field=models.CharField(max_length=50),
        ),
    ]
