# Generated by Django 5.1.6 on 2025-03-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_initialization",
            "0004_alter_kobotoolboxconfig_user_alter_logentry_user",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kobotoolboxconfig",
            name="token_form_objectif_vaccination",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kobotoolboxconfig",
            name="uid_form_objectif_vaccination",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
