# Generated by Django 5.1.7 on 2025-05-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_initialization', '0005_kobotoolboxconfig_token_form_objectif_vaccination_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KoboToolboxConfig',
        ),
    ]
