# Generated by Django 4.2 on 2025-09-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('server_url', models.URLField()),
                ('asset_uid', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('pull', 'Pull'), ('push', 'Push'), ('both', 'Both')], default='both', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('server_url', 'asset_uid')},
            },
        ),
        migrations.CreateModel(
            name='RawSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100)),
                ('submission_id', models.CharField(blank=True, max_length=50, null=True)),
                ('xform_id', models.CharField(blank=True, max_length=100, null=True)),
                ('form_version', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kobo_bridge.kobosource')),
            ],
        ),
        migrations.AddIndex(
            model_name='rawsubmission',
            index=models.Index(fields=['source', 'submitted_at'], name='kobo_bridge_source__df30ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawsubmission',
            unique_together={('source', 'instance_id')},
        ),
    ]
