# Generated by Django 4.2 on 2025-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo_bridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawsubmission',
            name='kobo_bridge_source__df30ef_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rawsubmission',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='rawsubmission',
            index=models.Index(fields=['source', 'instance_id'], name='kobo_bridge_source__1ca32e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsubmission',
            index=models.Index(fields=['submitted_at'], name='kobo_bridge_submitt_5d4861_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawsubmission',
            constraint=models.UniqueConstraint(fields=('source', 'instance_id'), name='uniq_source_instance'),
        ),
    ]
