# Generated by Django 5.1.7 on 2025-04-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commune', '0003_alter_commune_user'),
        ('Departement', '0003_alter_departement_user'),
        ('Region', '0002_region_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('necessite_avis_ordre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('delivre', 'Délivré')], default='en_cours', max_length=50)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('nom_etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('type_import', models.CharField(blank=True, max_length=255, null=True)),
                ('type_transformation', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actes_admin.categorieacte')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Commune.commune')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Departement.departement')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Region.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='justificatifs/')),
                ('nom', models.CharField(max_length=255)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='actes_admin.demandeacte')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('departemental', 'Départemental'), ('regional', 'Régional'), ('central', 'Central'), ('ordre', 'Ordre des vétérinaires'), ('ministere', 'Ministère')], max_length=50)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('delivre', 'Délivré')], max_length=50)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='actes_admin.demandeacte')),
            ],
        ),
        migrations.CreateModel(
            name='TypeActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validite', models.CharField(choices=[('1_mois', '1 mois'), ('2_mois', '2 mois'), ('3_mois', '3 mois'), ('6_mois', '6 mois'), ('1_an', '1 an'), ('2_ans', '2 ans'), ('3_ans', '3 ans'), ('sans_limite', 'Sans limite')], default='sans_limite', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='actes_admin.categorieacte')),
            ],
        ),
        migrations.AddField(
            model_name='demandeacte',
            name='acte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actes_admin.typeacte'),
        ),
    ]
