# Generated by Django 5.1.7 on 2025-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeacte',
            name='document_final',
            field=models.FileField(blank=True, null=True, upload_to='documents_actes_signes/'),
        ),
    ]
