# Generated by Django 5.1.7 on 2025-04-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actes_admin', '0002_demandeacte_document_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeacte',
            old_name='type_import',
            new_name='nom_unité_transformation',
        ),
        migrations.RenameField(
            model_name='demandeacte',
            old_name='type_transformation',
            new_name='noproduit_importe_ou_exporte',
        ),
    ]
