# Generated by Django 5.1.7 on 2025-04-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actes_admin', '0003_rename_type_import_demandeacte_nom_unité_transformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeacte',
            old_name='noproduit_importe_ou_exporte',
            new_name='nom_produit_importe_ou_exporte',
        ),
    ]
