# Generated by Django 5.1.7 on 2025-04-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departement', '0003_alter_departement_user'),
        ('Region', '0002_region_user'),
        ('actes_admin', '0004_rename_noproduit_importe_ou_exporte_demandeacte_nom_produit_importe_ou_exporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('departemental', 'Départemental'), ('regional', 'Régional'), ('central', 'Central'), ('ordre', 'Ordre des vétérinaires'), ('ministere', 'Ministère')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Departement.departement')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Region.region')),
            ],
        ),
    ]
