# Generated by Django 5.1.7 on 2025-04-10 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes_admin', '0005_emailnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_affectees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='actes_admin.demandeacte')),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_attribuees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
