# Generated by Django 5.1.7 on 2025-04-14 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes_admin', '0006_affectationsuivi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationsuivi',
            options={'verbose_name': 'Affectation de suivi', 'verbose_name_plural': 'Affectations de suivi'},
        ),
        migrations.AlterUniqueTogether(
            name='affectationsuivi',
            unique_together={('demande', 'agent')},
        ),
        migrations.CreateModel(
            name='PieceAFournir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piece', models.CharField(max_length=255, verbose_name='Nom de la pièce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description ou précision')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire ?')),
                ('type_acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='actes_admin.typeacte')),
            ],
        ),
    ]
